"use client";
import "./globals.css";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/Sidebar";

// export const metadata = {
//   title: "Foo",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showSideBar = pathname === "/" ? false : true;
  return (
    <>
      <head>
        <link rel="shortcut icon" href="/assets/logo.png" />
      </head>
      <html lang="en">
        <body>
          {showSideBar && <Sidebar />}
          {children}
        </body>
      </html>
    </>
  );
}
