"use client";
import "./globals.css";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./GlobalRedux/provider";

// export const metadata = {
//   title: "Foo",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showSideBar = pathname === "/" ? false : true;
  return (
    <>
      <html lang="en">
        <body>
          <Providers>
            {showSideBar && <Sidebar />}
            {children}
          </Providers>
        </body>
      </html>
    </>
  );
}
